Repository icatproject/ids.server, pull requests merged in 2023-08, with the labels that each got.

#135 Drop the test case for file size null in FileCheckerTest
  src/test/java/org/icatproject/ids/integration/one/FileCheckerTest.java
  src/test/java/org/icatproject/ids/integration/two/FileCheckerTest.java
Labels: compatibility, test suite

#138 Upgrade to JakartaEE 10 API for compatibility with Payara 6
  .github/workflows/ci-build.yml
  pom.xml
  src/main/java/org/icatproject/ids/CORSResponseFilter.java
  src/main/java/org/icatproject/ids/DataSelection.java
  src/main/java/org/icatproject/ids/FileChecker.java
  src/main/java/org/icatproject/ids/FiniteStateMachine.java
  src/main/java/org/icatproject/ids/ICATGetter.java
  src/main/java/org/icatproject/ids/IcatReader.java
  src/main/java/org/icatproject/ids/IdsBean.java
  src/main/java/org/icatproject/ids/IdsService.java
  src/main/java/org/icatproject/ids/LockManager.java
  src/main/java/org/icatproject/ids/PropertyHandler.java
  src/main/java/org/icatproject/ids/Tidier.java
  src/main/java/org/icatproject/ids/Transmitter.java
  src/main/java/org/icatproject/ids/exceptions/IdsExceptionMapper.java
  src/main/java/org/icatproject/ids/exceptions/NotFoundExceptionMapper.java
  src/main/java/org/icatproject/ids/exceptions/RuntimeExceptionMapper.java
  src/main/scripts/setup
  src/main/webapp/WEB-INF/web.xml
  src/site/xhtml/release-notes.xhtml
  src/test/java/org/icatproject/ids/DataSelectionDevTest.java
  src/test/java/org/icatproject/ids/integration/BaseTest.java
  src/test/java/org/icatproject/ids/integration/util/client/TestingClient.java
Labels: compatibility

#141 Fix setup script: filesCheck.parallelCount and linkLifetimeSeconds are optional
  src/main/scripts/setup
Labels: bug
